version: '3.5'
services:
  redis:
    extends:
      file: redis.yaml
      service: redis

  mysql:
    extends:
      file: mysql.yaml
      service: mysql
  nginx:
    extends: 
      file: nginx.yaml
      service: nginx

