version: '3.5'
services:
  nginx:
    image: nginx:stable
    container_name: fudy-nginx
    ports:
      - 80:80
    volumes:
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/docker/nginx/logs:/var/log/nginx
    privileged: true
