
version: '3.5'
services:
  redis:
    image: redis:6.0.3
    container_name: my-redis
    ports:
      - 6379:6379
    volumes:
      - /opt/docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - /opt/docker/redis/data:/data
    command:
      /bin/bash -c "redis-server /etc/redis/redis.conf"
  restart: always
